### ISSUE TITLE
Feature Request: Strip URL query string at end

### ISSUE THREAD

**Issue by ericpardee** [pnlng/alfred-url-actions#1]
Example input: 
`https://www.sandiegouniontribune.com/communities/north-county/oceanside/story/2021-08-04/oceanside-overturns-approval-of-amazon-distribution-center?utm_id=34807&sfmc_id=3422418`

Example output: 
`https://www.sandiegouniontribune.com/communities/north-county/oceanside/story/2021-08-04/oceanside-overturns-approval-of-amazon-distribution-center`

**Comment by pnlng** [comment]
Great idea. I've released a [new version](https://github.com/pnlng/alfred-url-actions/releases/tag/v1.1.6) with this feature.
