### ISSUE TITLE
Failed in macOS 12.3

### ISSUE THREAD

**Issue by HybridRbt** [pnlng/alfred-url-actions#2]
This was working all fine until I upgraded to macOS 12.3. I would assume it's because Apple removed python 2 since this release?

**Comment by pnlng** [comment]
Thanks for reporting this. The [latest version](https://github.com/pnlng/alfred-url-actions/releases/tag/v1.1.7) no longer requires Python. (It bundles a binary file; the code has been ported to Go.)
